name: Build Cult & Release
on: 
  push:
    tags: 
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
    - name: Compile
      run: javac --enable-preview --source 22 -d target src/Main.java && java --enable-preview -cp target Main build
    - uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
          ./target/jar/cult-${{ github.ref }}.jar
