name: Build Cult & Release
on: 
  push:
    tags: 
      - v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
    - name: Compile
      run: java --enable-preview --source 22 src/Main.java build --fat
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v} | sed 's/-alpha//g'
    - uses: softprops/action-gh-release@v2
      with:
        draft: true
        token: ${{ secrets.CULT_RELEASE }}
        files: |
          ./target/jar/cult-${{ steps.get_version.outputs.VERSION }}.jar
